development:
  adapter: sqlserver
  mode: dblib
  
  username: sa
  password: 12345678
  database: lineage_w_bank_dev  
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: lineage_w_bank
  pool: 5
  timeout: 5000